# Generated by Django 5.1.6 on 2025-03-10 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
