# Generated by Django 5.1.6 on 2025-12-01 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(blank=True, default='default_influencer.png', null=True, upload_to='influencer_thumbs/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=30)),
                ('sns_link', models.URLField(blank=True, max_length=400, null=True)),
                ('followers', models.PositiveBigIntegerField(blank=True, help_text='수동/자동으로 업데이트 가능', null=True)),
                ('min_price', models.PositiveIntegerField(default=0)),
                ('max_price', models.PositiveIntegerField(default=0)),
                ('categories', models.CharField(blank=True, help_text='콤마로 구분된 카테고리', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer Profile',
                'verbose_name_plural': 'Influencer Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['display_name'], name='influencers_display_ae9b75_idx'), models.Index(fields=['method'], name='influencers_method_161d2c_idx')],
            },
        ),
    ]
