# Generated by Django 5.1.6 on 2025-12-01 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiserList', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(blank=True, default='default_advertiser.png', null=True, upload_to='advertiser_thumbs/')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='콤마로 구분된 태그 (예: fashion,cosmetics)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertiser Profile',
                'verbose_name_plural': 'Advertiser Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='advertiserList',
        ),
        migrations.AddIndex(
            model_name='advertiserprofile',
            index=models.Index(fields=['name'], name='advertiserL_name_0864ba_idx'),
        ),
    ]
